//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nedvijimost_.DataApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nedvigimostEntities : DbContext
    {
        public nedvigimostEntities()
            : base("name=nedvigimostEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rielty> rielty { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user_admin> user_admin { get; set; }
        public virtual DbSet<user_client> user_client { get; set; }
        public virtual DbSet<user_rieltor> user_rieltor { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<user_status> user_status { get; set; }
    }
}
